---
title: "Plot of radial profile"
output: html_document
abstract: ""
---


```{r}

devtools::load_all()

densityFiles <- list.files(
    system.file("yifengData", package="ColonDNATopology"),
    pattern="density_normalized_comb", full.names=TRUE )

densityData <- lapply(densityFiles, read.delim, header=FALSE, sep=" ")
names(densityData) <- gsub("density_normalized_comb_|.txt", "",
                           basename( densityFiles ))

densityData <- lapply(names(densityData), function(x){
    densityData[[x]] <- densityData[[x]][,1:4]
    colnames(densityData[[x]]) <- c("x", "A", "B", "NAs")
    densityData[[x]]$sample <- x
    densityData[[x]]
} )

densityData <- do.call(rbind, densityData)

library(magrittr)

densityData <- dplyr::select( densityData, x, A, B, sample ) %>%
    reshape2::melt( id.vars=c("x", "sample") )

densityData <- densityData %>%
    dplyr::mutate(
               grp = paste0( sample, variable ),
               type = ifelse( grepl( "N$", sample ), "Normal", "Tumor" ) )

densityData$type <- factor( densityData$type )
levels(densityData$type) <- c("N", "T")

##scaleCols <- c(T="#b2182b", N="#2166ac")
scaleCols <- c(T="#762a8390", N="#1b783790")
scaleCols <- c(T="#984ea3", N="#4daf4a")

```

```{r, fig.height=1.8, fig.width=3.5}
## png( "../output/plots/densities_yifeng_v2.png",
##    height=1.8, width=3.5, unit="in", res=300 )
library(ggplot2)
library(cowplot)
theme_set(theme_cowplot())
ggplot( densityData, aes( x, value, col=type, group=grp ) ) +
    geom_line( size=0.35 ) +
    labs(x="Radial position", y=expression("Density (x"~10^-4*")"), col="") + 
    facet_grid( ~variable ) +
    scale_x_continuous(breaks=seq(0, 1, 0.5), labels=c("0", "0.5", "1")) +
    scale_y_continuous(breaks=seq(0, 4e-04, 2e-04), labels = c(0, 2, 4)) +
    theme(axis.line=element_blank()) +
    scale_color_manual(values=scaleCols) +
    panel_border( size=1, colour="black" )
##dev.off()

```
