---
title: "Enhancer promoter loops in colon tissue and colon normals"
output: html_document
abstract: "Analysis of TADs"
---

## Reformating data

```{r}

devtools::load_all()
data(ctcfCounts)
data(ctcfPeaks)

library(DESeq2)

chip <- DESeqDataSetFromMatrix(
    ctcfCounts,
    colData=DataFrame(sample=colnames(ctcfCounts)),
    design=~1 )

vst <- varianceStabilizingTransformation( chip )
colData(vst)$sample <- rownames(colData(vst))
colData(vst)$label <- ifelse( colData(vst)$sample %in% c("BRD3162", "BRD3179"), "CIMP",
                      ifelse( grepl("N$", colData(vst)$sample), "Normal", "Tumor" ))

library(gridExtra)
dat <- DESeq2::plotPCA(vst, intgroup="label", ntop=20000, returnData=TRUE)

colData(chip)$pc1 <- dat$PC1
colData(chip)$fact <- factor(ifelse(dat$PC1 > 0, "fact1", "fact2"))
colData(vst)$sample2 <- gsub("-REP2", "", colData(vst)$sample)

rowRanges(chip) <- ctcfPeaks

data(segmentation_40K)
cnvs <- segmentation_40K
rownames(chip) <- sprintf("peak%0.6d", seq_len(nrow(chip)))
chip <- chip[as.character(seqnames( chip )) %in% as.character( seqnames( cnvs ) ),]

```

## Test CIMP vs others

```{r}

library(limma)

cimpVAll <- chip
colData(cimpVAll)$type <-
                    factor( ifelse( rownames( colData( cimpVAll ) ) %in% c("BRD3162", "BRD3179"),
                                   "CIMP", "nother" ) )
design(cimpVAll) <- ~ fact + type

cimpVAll <- copyNumberNormalize( cimpVAll, cnvs )
cimpVAll <- normalizeTrend( cimpVAll )
cimpVAll <- DESeq( cimpVAll )
cimpVAllRes <- results(
    cimpVAll,
    contrast=c("type", "CIMP", "nother"),
    lfcThreshold=0 )

cimpVAllRes$CIMP <-
    rowMeans( counts( cimpVAll, normalized=TRUE )[,colData(cimpVAll)$type == "CIMP"] )
cimpVAllRes$nother <-
    rowMeans( counts( cimpVAll, normalized=TRUE )[,colData(cimpVAll)$type == "nother"] )
cimpVAllRes$NonCIMP <-
    rowMeans( counts( cimpVAll, normalized=TRUE )[,colData(cimpVAll)$type == "nother"] )

```

## Test CIMP vs other (Islands)

```{r}

cimpVAllIsland <- chip
colData(cimpVAllIsland)$type <-
                          factor( ifelse( rownames( colData( cimpVAllIsland ) ) %in% c("BRD3162", "BRD3179"),
                                         "CIMP", "nother" ) )
design(cimpVAllIsland) <- ~fact + type

data(cgi)
seqlevelsStyle( cgi ) <- "UCSC"
cgi_shore <- c(flank(cgi, width = 2000, start=TRUE),
               flank(cgi, width = 2000, start=FALSE))

cimpVAllIsland <- subsetByOverlaps( cimpVAllIsland, c(cgi, cgi_shore))
cimpVAllIsland <- copyNumberNormalize( cimpVAllIsland, cnvs )
cimpVAllIsland <- normalizeTrend( cimpVAllIsland )
cimpVAllIsland <- DESeq( cimpVAllIsland )
cimpVAllIslandRes <- results( cimpVAllIsland,
                       contrast=c("type", "CIMP", "nother"),
                       lfcThreshold=0 )
cimpVAllIslandRes$CIMP <-
    rowMeans( counts( cimpVAllIsland, normalized=TRUE )[,colData(cimpVAll)$type == "CIMP"] )
cimpVAllIslandRes$NonCIMP <-
    rowMeans( counts( cimpVAllIsland, normalized=TRUE )[,colData(cimpVAll)$type == "nother"] )

cimpvsAllRes <- rowRanges(chip)
mcols( cimpvsAllRes ) <- cimpVAllRes

cimpvsAllIslandRes <- rowRanges(chip)
cimpvsAllIslandRes <- cimpvsAllIslandRes[rownames(cimpVAllIslandRes),]
mcols(cimpvsAllIslandRes) <- cimpVAllIslandRes

```


```{r}

library(bsseq)
library(HDF5Array)
bsseq <- loadHDF5SummarizedExperiment(system.file( "hdf5", "se_hdf5", package="ColonDNATopology" ))

colData(bsseq)$origin <- 
  ifelse( colnames(bsseq) %in% c("FHC") | grepl("N$", colnames(bsseq) ), "normal", "COAD" )
colData(bsseq)$originType <- ifelse( grepl("BRD|MGH", colnames(bsseq)), "primaryTissue", "cellLine")
colData(bsseq)$originType[grep("5AZA|DMSO", colData(bsseq)$sample_id)] <- "AZAExp"
colData(bsseq)$sample_id <- colnames(bsseq)

methCTCF <- getMeanMeth( bsseq, rowRanges(chip) )
methCTCF <- methCTCF[,grepl("BRD|MGH", colnames(methCTCF))]
library(magrittr)

cData <- data.frame( sample=colnames( methCTCF ) ) %>%
    dplyr::mutate(
               type=dplyr::case_when(
                   sample %in% c("BRD3162", "BRD3179") ~ "CIMP",
                   grepl( "N$", sample ) ~ "Normal",
                   TRUE ~ "Tumor"
                   ) )

methMean <- as.data.frame( sapply( split( as.character( cData$sample ), cData$type ), function(x){
    rowMeans( as.data.frame( methCTCF[,x] ), na.rm=TRUE )
} ) )
methMean$NonCIMP <-
    rowMeans( as.data.frame( methCTCF )[,as.character(cData$sample)[cData$type != "CIMP"]], na.rm=TRUE )

mcols(cimpvsAllRes)$methCIMP <- methMean$CIMP
mcols(cimpvsAllRes)$methNonCIMP <- methMean$NonCIMP
mcols(cimpvsAllRes)$methDiff <- methMean$CIMP - methMean$NonCIMP
#mcols(cimpvsAllRes)$NonCIMP <- mcols(cimpvsAllRes)$NonCIMP


islandPeaks <- names(cimpvsAllIslandRes)

mcols(cimpvsAllIslandRes)$methCIMP <- methMean[islandPeaks,"CIMP"]
mcols(cimpvsAllIslandRes)$methNonCIMP <- methMean[islandPeaks,"NonCIMP"]
mcols(cimpvsAllIslandRes)$methDiff <- mcols(cimpvsAllIslandRes)$methCIMP - mcols(cimpvsAllIslandRes)$methNonCIMP

```

## Volcano plot


```{r}

data(cohort_data)
data(boundaryScores)

boundary_cutoff <- qnorm(0.9)

#boundaries2 <- dplyr::ungroup(readRDS("/data/aryee/bernstein/hic/SummarizedData/TADs/boundary_scores.rds"))
#boundaries2 <- unique( as.data.frame( boundaries2 )[,c("chr", "pos")] )

boundaries <- boundaryScores %>%
    dplyr::filter( bin_num %in% c(10, 20, 50) ) %>%
    dplyr::filter( sampleID %in% cohort1IDs ) %>%
    dplyr::group_by( bin_num, sampleID ) %>%
    dplyr::mutate( norm=(within_vs_cross-median(within_vs_cross))/mad(within_vs_cross) ) %>%
    dplyr::filter( norm > boundary_cutoff ) %>%
    dplyr::group_by( chr, pos ) %>%
    dplyr::mutate( norm_max=max(norm) ) %>%
    dplyr::select( chr, pos, norm_max ) %>%
    dplyr::ungroup()

boundaries$regionIdx <- cumsum(c(TRUE, diff(boundaries$pos)>2*40000)) 

boundaries <- boundaries %>%
    dplyr::group_by(regionIdx) %>%
    dplyr::top_n(1, norm_max)

boundaryInfo <- GRanges( boundaries$chr, IRanges(boundaries$pos, boundaries$pos))

mcols(cimpvsAllIslandRes)$dist2boundary <- 
    mcols(distanceToNearest( cimpvsAllIslandRes, boundaryInfo ))$distance

mcols(cimpvsAllRes)$dist2boundary <- 
    mcols(distanceToNearest( cimpvsAllRes, boundaryInfo ))$distance

cimpPl <- as.data.frame( cimpvsAllIslandRes ) %>%
    dplyr::filter( baseMean > 5, dist2boundary < 60000 ) %>%
    dplyr::mutate( met=ifelse(methDiff > 0.15, "Hypermethylated", "Not hypermethylated") ) %>%
    dplyr::select( log2FoldChange, pvalue, met, methDiff  ) %>%
    na.omit()

```

```{r, fig.width=2.2, fig.height=2.8, out.width = "75%"}

library(ggplot2)
library(cowplot)
theme_set(theme_cowplot())

#png("../output/plots/volcano_ctcf_meth.png", unit="in", res=300, height=2.8, width=2.2)
dplyr::filter( cimpPl, met == "Not hypermethylated")  %>%
    ggplot( aes( log2FoldChange, -log10( pvalue ) ) ) +
    geom_point( alpha=0.5, size=0.5) +
    geom_point(
        data=dplyr::mutate( dplyr::filter( cimpPl, methDiff > 0.15 ),
                           met="Hypermethylated"),
        mapping=aes( log2FoldChange, -log10(pvalue), col=met), size=0.5, alpha=0.5 ) +
    ylim(0, 7) +
    xlim(-4, 4) +
    xlab(bquote("CTCF fc"~"("*log[2]*")")) +
    ylab(italic(p)*"-value"~"("*-log[10]*")") +
    theme( legend.pos="top", legend.text=element_text(size=10) ) + labs(col="") +
    guides(colour = guide_legend(override.aes = list(size=1.6, alpha=1))) +
    scale_colour_manual(values=c(`Hypermethylated`="red") )#, `Not hypermethylated`="#00000090") )
#dev.off()
```

```{r}

object <- cimpVAllRes
objectAll <- cimpVAll

xx <- which( object$padj < 0.1 & object$log2FoldChange < 0 )

signalMat <- log2( counts( objectAll[,!grepl("REP2", colData( objectAll )$sample)], normalized=TRUE ) + 1 )
#xx <- head( order( rowVars( signalMat ), decreasing=TRUE ), 1000 )
colLabs <- ifelse( colnames(signalMat) %in% c("BRD3162", "BRD3179"), "CIMP",
           ifelse( grepl("N$", colnames(signalMat)), "Normal", "Tumor") )

signalMat <- sapply( split( seq_len( ncol( signalMat ) ), colLabs ), function(x){
    rowMeans( signalMat[xx,x] )
} )
signalMat <- signalMat - rowMeans( signalMat )
ylims <- c(0, 1)
signalMat <- pmax( pmin( signalMat, quantile( signalMat, 0.995 ) ), quantile( signalMat, 0.005) )

scaledMat <- scales::rescale( signalMat, ylims )

methLong <- reshape2::melt( as.matrix(methMean[rownames(scaledMat),c("CIMP", "Normal", "Tumor")]),
                           varnames=c("peak", "group"), value.name="signal")
methLong$type <- "Methylation"
ctcfLong <- reshape2::melt( scaledMat, varnames=c("peak", "group"), value.name="signal" )
ctcfLong$type <- "CTCF"
longData <- rbind( methLong, ctcfLong )
longData$group <- factor( longData$group, levels=c("Normal", "Tumor", "CIMP") )
originalBreaks <- c(-1.5, 0, 1.5)
breaks <- scales::rescale( c(originalBreaks, range(signalMat) ), to=ylims)[1:3]
longData$type <- factor( longData$type, levels=c("Methylation", "CTCF") )
ctCol <- "#737373"


```

```{r, fig.width=3.5, fig.height=3, out.width='75%'}

##png("../output/plots/boxplot_doubleaxis.png", width=3.5, height=3, unit="in", res=300)
longData %>%
    ggplot( aes( group, signal, col=type ) ) +
    geom_boxplot(outlier.size=0.2) +
    coord_cartesian(ylim=ylims) +
    scale_y_continuous(sec.axis = sec_axis(~.*1, name = "CTCF",
                                           breaks = breaks, labels=originalBreaks) ) +
##    scale_colour_manual( values=c( Lost="red", Stable="#666666" ) ) +
    geom_vline(xintercept=c(1.5, 2.5) ) +
    panel_border(colour="black", size=1) +
    theme(
        axis.line=element_blank(), legend.pos="top",
        axis.text.y.right = element_text(color = ctCol),
        axis.title.y.right=element_text(color=ctCol),
        axis.ticks.y.right=element_line(color=ctCol)) +
    labs( x="", y="Methylation", col="") +
    scale_colour_manual( values=c( CTCF=ctCol, Methylation="#000000" ) )
## dev.off()

```
